### ISSUE TITLE
[0.0.6] doesn't work for facebook.com (works for other domains)

### ISSUE THREAD

**Issue by lguminski** [denisix/whois-node-json#1]
It a nice little lib, but it is unstable. Sometimes it works, sometimes doesn't. It clearly has a problem with processing facebook.com whois data

```
var whois = require('whois-node-json');
whois('facebook.com').then((data: any) => console.log(`retrieved `, data));
```

results in 
```
node_modules/.pnpm/whois-node-json@0.0.6/node_modules/whois-node-json/whois.js:165
          .reduce((a, b, c) => {
           ^
RangeError: Invalid array length
    at node_modules/.pnpm/whois-node-json@0.0.6/node_modules/whois-node-json/whois.js:168:24
    at Array.reduce (<anonymous>)
    at whois (node_modules/.pnpm/whois-node-json@0.0.6/node_modules/whois-node-json/whois.js:165:12)
    at Object.<anonymous> (b.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module.m._compile (node_modules/.pnpm/ts-node@10.9.1_cbe7ovvae6zqfnmtgctpgpys54/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require.extensions.<computed> [as .ts] (node_modules/.pnpm/ts-node@10.9.1_cbe7ovvae6zqfnmtgctpgpys54/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
```

**Comment by denisix** [comment]
there was an issue with string ending, fixed, please check now :)
